### ISSUE TITLE
Only one Extender works & No color scribble strips.

### ISSUE THREAD

**Issue by Swiftacus** [bramdebouvere/fltouch#16]
I have no script for a second extender in the download.

**Comment by bramdebouvere** [comment]
Hi there.

You need to use the same extender script for the first and the second extender.

Also, please try to update FL studio to the latest release available on the website.
If after that still only one of the extenders works, please make sure the device firmware is updated both on your main X-Touch unit and on both of the extenders.

Also, please make sure that you are using the actual FLtouch scripts, not the built in Mackie Control scripts. These are the ones you want:
![afbeelding](https://user-images.githubusercontent.com/3641681/186125754-c1518607-dc9b-480b-9a40-4c2b70f89d9f.png)

**Comment by bramdebouvere** [comment]
Hey Swiftacus, have you been able to resolve the issue using my feedback?
Please let me know.
